name: DockerHub CD
on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: ssh
        uses: cross-the-world/ssh-scp-ssh-pipelines@late
        with:
          host: ${{ secrets.AWS_IP }}
          user: "ubuntu"
          key: ${{ secrets.AWS_KEY }}  
          connect_timeout: 10s
          first_ssh: |
            sudo docker stop mtg-card-manager
            sudo docker rm mtg-card-manager
            sudo docker compose up -d
      - name: Checkout
        uses: actions/checkout@v5
      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v6.18.0
        with:
          push: true
          tags: oceansforce684/primer_repo:${{ env.RELEASE_VERSION }}
