name: miprimeracion

on: 
  push:
    branches:
      - main

jobs:
   lamine:
      runs-on: ubuntu-latest
      steps:
        - name: Primera accion
          run: echo "Hola mundo"
        - name: Setup Java JDK
          uses: actions/setup-java@v5.0.0
