name: miprimeracion

on: 
  push:
    branches:
      - main

jobs:
   lamine:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4

        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'temurin'
        - name: Test
          run: mvn -B test --file Test/sumar/src/test/java/com/ejemplo/TestCalculadora.java
