name: miprimeracion

on: 
  push:
    branches:
      - main

jobs:
   lamine:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4

        - run: ls -l

        - run: cd Test/sumar

        - run: pwd

        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'temurin'
        - name: Test
          working-directory: ./Test/sumar
          #run: mvn -B test --file Test/sumar/src/test/java/com/ejemplo/TestCalculadora.java
          run: mvn test